services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: "WARN"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: financial-crime-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: "WARN"
      KAFKA_LOG4J_LOGGERS: "org.apache.zookeeper=WARN,kafka.zookeeper=WARN,kafka.server=WARN,kafka.log=WARN,org.apache.kafka=WARN,kafka.network=WARN,kafka.controller=WARN,state.change.logger=WARN,kafka.zk=WARN,kafka.coordinator=WARN,kafka.cluster=WARN,kafka.utils=WARN,kafka.common=WARN"
    depends_on:
      - zookeeper
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: financial-crime-api
    ports:
      - "8000:8000"
    volumes:
      - feast_data:/app/financial_crime/feature_store/feature_repo/data
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: financial-crime-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=error
    restart: unless-stopped

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: financial-crime-producer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: financial-crime-consumer
    volumes:
      - feast_data:/app/financial_crime/feature_store/feature_repo/data
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      API_URL: http://api:8000
    depends_on:
      - kafka
      - api
    restart: unless-stopped

volumes:
  feast_data:
