FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential make curl \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN make requirements

CMD ["uv", "run", "python", "-m", "financial_crime.kafka.consumer"]
